### ISSUE TITLE
Locale exceptions when trying to load product wow_classic

### ISSUE THREAD

**Issue by Ovahlord** [Marlamin/wow.tools.local#37]
The release build 0.6.2 apparently broke locale handling as trying to launch the app begins with an exception while initializing casc:

![grafik](https://github.com/user-attachments/assets/5ec130bb-7d83-495d-bf03-9e0fe87b95a7)

When trying to switch to one of the classic builds (like 4.4.1) from within the UI, you get another exception which causes the switching process to freeze, rendering the application unusable. This is apparently also related to the broken locale initialization. The 4.4.1 client that I'm using has all available EU locales installed. The only config change I made was to change the product to wow_classic in order to detect the classic builds.

The error log:
```
Initializing CASC from local disk with basedir F:\Games\WoW Cataclysm Classic\World of Warcraft and program wow_classic and locale enUS
CDNIndexHandler.Initialize() completed in 00:00:01.2076753
FileIndexHandler() completed in 00:00:00.0032702
LocalIndexHandler.Initialize() completed in 00:00:00.2492851
new EncodingHandler() completed in 00:00:00.5973925
new RootHandler() completed in 00:00:00.0008326
new CASCHandler() completed in 00:00:02.1827575
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN98RKKKP6DG", Request id "0HN98RKKKP6DG:0000000C": An unhandled exception was thrown by the application.
      System.IO.InvalidDataException: block.LocaleFlags == LocaleFlags.None
         at CASCLib.WowRootHandler..ctor(BinaryReader stream, BackgroundWorkerEx worker) in D:\a\wow.tools.local\wow.tools.local\CascLib\CascLib\RootHandlers\WowRootHandler.cs:line 199
         at CASCLib.CASCHandler..ctor(CASCConfig config, BackgroundWorkerEx worker) in D:\a\wow.tools.local\wow.tools.local\CascLib\CascLib\CASCHandler.cs:line 76
         at CASCLib.CASCHandler.Open(CASCConfig config, BackgroundWorkerEx worker) in D:\a\wow.tools.local\wow.tools.local\CascLib\CascLib\CASCHandler.cs:line 135
         at CASCLib.CASCHandler.OpenLocalStorage(String basePath, String product, BackgroundWorkerEx worker) in D:\a\wow.tools.local\wow.tools.local\CascLib\CascLib\CASCHandler.cs:line 119
         at wow.tools.local.Services.CASC.InitCasc(String basedir, String program, LocaleFlags locale) in D:\a\wow.tools.local\wow.tools.local\Services\CASC.cs:line 83
         at lambda_method11(Closure, Object, Object[])
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Marlamin** [comment]
This is probably expected behavior right now due to the root fixes for 11.1 being incomplete in the current build. It should already be fixed in the next one, but will leave open to verify that once that ships post 11.1 PTR release in the next week or so.

**Comment by Ovahlord** [comment]
Yeah, this is fixed in latest head. Just built the source myself to test it and it's doing it's just just fine now

**Comment by Marlamin** [comment]
Awesome, thanks. Will close as I expect 11.1 any day now.
